
base: []
seed: 1000
model:
    kind: GIN
    kwargs:
        num_tasks: 1
        num_layers: 2
        hidden: 128
        use_fp: True
        leaf_depth: 0
dataset:
    raw_data_dir_list: ['../DPI_Data/DA_IC50_specific_model_tsvs/specific_datasets/protein_0008']
    processed_data_dir_list: ['../DPI_Data/DA_IC50_specific_model_tsvs/processed_specific_datasets/protein_0008']
    train_batch_size: 64
    eval_batch_size: 64
    num_workers: 0
training:
    num_epochs: 10
    num_iters_per_epoch: 1500
    log_freq: 100
    optimizer:
        kind: Adam
        kwargs:
            weight_decay: 0.0001        
    criterions: [{kind: MSELoss, kwargs: {}}]
    scheduler:
        kind: CosineAnnealingWithWarmUp
        kwargs:
            start_lr: 0.
            base_lr: 0.0001
            final_lr: 0.
            num_warmup_epochs: 1
            num_cosine_epochs: 9
